[package]
name = "haddock-restraints-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "haddock_restraints"
crate-type = ["cdylib"]

[dependencies]
haddock-restraints = "0.10"
pyo3 = { version = "0.15", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = "0.26"
